<a href="https://colab.research.google.com/github/JohnAquino15/Numerical-Methods-58012/blob/main/Python_Exercice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##John Benedict Aquino

In [15]:
import numpy as np
A = np.array([[-5,0],[4,1]]) #Matrix A
print(A)

[[-5  0]
 [ 4  1]]


In [16]:
B = np.array([[6,-3],[2,3]]) #Matrix B
print(B)

[[ 6 -3]
 [ 2  3]]


In [17]:
#Question 1

sum = A + B
print(sum)

[[ 1 -3]
 [ 6  4]]


In [18]:
#Question 2

difference1 = B - A
print(difference1)

[[11 -3]
 [-2  2]]


In [19]:
#Question 3

difference2 = A - B
print(difference2)

[[-11   3]
 [  2  -2]]
